name: Full Stack CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Files
        run: ls

      - name: Print Message
        run: echo "GitHub Actions Workflow Running Successfully"
