name: Full Stack CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show message
        run: echo "GitHub Actions pipeline is running successfully"
